language:       node_js
node_js:
  - "8"
  - "6"
dist:           trusty
after_success:
  - npm run coverage-publish
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: 'latest'
